---
title: "results-votes"
author: "Joe Ciesielski"
date: "2/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(tidymodels)
library(jtcr)
library(plotly)

bill_votes <- read_csv(here::here("data/bill_votes.csv"))

bills <- read_csv(here::here("data/pa house bills 2017-18.csv"))

election <- read_csv(here::here("data/election_results.csv"))

vote_names <- read_csv(here::here("data/votes_names.csv"))

reps_2018 <- read_csv(here::here("data/reps_2018.csv"))

```

```{r}

reps <- election %>% 
  mutate(
    representative = case_when(
      pct_dem > 0.5 ~ dem,
      pct_dem < 0.5 ~ rep,
      TRUE ~ NA_character_
    ),
    pct_win = case_when(
      representative == dem ~ pct_dem,
      representative == rep ~ 1 - pct_dem,
      TRUE ~ NA_real_
    ),
    party = case_when(
      pct_dem > 0.5 ~ "dem",
      pct_dem < 0.5 ~ "rep",
      TRUE ~ NA_character_ 
    )
  ) %>% 
  select(representative, pct_win, party) %>% 
  left_join(vote_names, by = c("representative" = "election_name")) %>% 
  left_join(reps_2018, by = c("representative" = "rep")) %>% 
  rename(rep_2018 = winner) %>% 
  replace_na(list(rep_2018 = 0))

bill_votes_progressive <- bill_votes %>% 
  left_join(bills %>% select(bill, topic, progressive), by = "bill")

win_share_voting <- bill_votes_progressive %>% 
  left_join(reps, by = c("rep" = "vote_name")) %>% 
  mutate(
    prog_vote = case_when(
      vote == "yay" & progressive == 1 ~ 1L,
      vote == "nay" & progressive == -1 ~ 1L,
      vote == "yay" & progressive == -1 ~ 0L,
      vote == "nay" & progressive == 1 ~ 0L,
      TRUE ~ NA_integer_
    )
  )

write_csv(win_share_voting, here::here("data/pahouse2016_votes_by_win_share.csv"))

missing_election_data <- win_share_voting %>% 
  filter(is.na(pct_win)) %>% 
  distinct(rep)

```

## Modeling

```{r}

rep_prog_votes <- win_share_voting %>% 
  filter(!is.na(pct_win)) %>% 
  group_by(rep, pct_win, party, rep_2018) %>% 
  summarise(prog_votes = mean(prog_vote))

rep_prog_votes %>% 
  ggplot(aes(pct_win, prog_votes, color = party)) +
    geom_point() +
    theme_jtc() +
    color_jtc("color")

```

prediction

```{r}

prog_mod <- lm(prog_votes ~ pct_win:party, data = rep_prog_votes)

prog_mod %>% 
  broom::tidy()

```

```{r}

augment(prog_mod) %>% 
  ggplot(aes(pct_win, .fitted, color = party)) +
    geom_point() +
    geom_line() +
    scale_y_continuous(limits = c(0,1), labels = scales::percent_format()) +
    theme_jtc() +
    color_jtc("color")

```


```{r}

dem_prog_pred <- data.frame(
  rep_prog_votes,
  augment(prog_mod)
) %>% 
  filter(party == "dem")

plot_text <- sprintf(
  "%s<br>election pct: %.2f <br>predicted: %.2f <br>residual: %.2f", 
  dem_prog_pred$rep, 
  dem_prog_pred$pct_win,
  dem_prog_pred$.fitted,
  dem_prog_pred$.resid
)

resid_plot <- dem_prog_pred %>% 
  mutate(rep = fct_reorder(rep, .resid)) %>% 
  ggplot(aes(pct_win, prog_votes)) +
    geom_jitter(aes(text = plot_text, alpha = rep_2018)) +
    geom_line(aes(y = .fitted), linetype = 3, color = "#002868") +
    scale_x_continuous(labels = scales::percent_format(2)) + 
    expand_limits(y = 0) + 
    theme_jtc() +
    labs(
      title = "Plenty of Democrats are less progressive than their win share predicts",
      x = "election win share",
      y = "proportion of progressive votes"
    )
    
ggplotly(resid_plot, tooltip = "text")
```

Is their residual predictive of whether they will not win in 2018?

```{r}

glm(rep_2018 ~ .resid, family = "binomial", data = dem_prog_pred) %>% 
  broom::tidy()

```

Not really.

```{r}
all_prog_pred <- data.frame(
  rep_prog_votes,
  augment(prog_mod)
)

plot_text <- sprintf(
  "%s<br>election pct: %.2f <br>predicted: %.2f <br>residual: %.2f", 
  all_prog_pred$rep, 
  all_prog_pred$pct_win,
  all_prog_pred$.fitted,
  all_prog_pred$.resid
)

all_resid_plot <- all_prog_pred %>% 
  mutate(rep = fct_reorder(rep, .resid)) %>% 
  ggplot(aes(pct_win, prog_votes, color = party)) +
    geom_jitter(aes(text = plot_text, alpha = rep_2018)) +
    geom_line(aes(y = .fitted), linetype = 3) +
    scale_x_continuous(labels = scales::percent_format(2)) + 
    expand_limits(y = 0) + 
    theme_jtc() +
    labs(
      x = "election win share",
      y = "proportion of progressive votes"
    )
    
ggplotly(all_resid_plot, tooltip = "text")

```

```{r}
glm(rep_2018 ~ .resid:party, family = "binomial", data = all_prog_pred) %>% 
  broom::tidy()
```

Notes:

### Reps more progressive than expected

```{r}

all_prog_pred %>% 
  filter(party == "rep") %>% 
  arrange(desc(.resid)) %>% 
  head(5)

```

- Murt
  - Montco
  - moderate, received endorsements from unions and decent [ratings](https://votesmart.org/candidate/58360/thomas-murt) from environmental groups

### Reps less progressive than expected

```{r}

all_prog_pred %>% 
  filter(party == "rep") %>% 
  arrange(.resid) %>% 
  head(5)

```

### Dems more progressive than expected

```{r}

all_prog_pred %>% 
  filter(party == "dem") %>% 
  arrange(desc(.resid)) %>% 
  head(5)

```

### Dems less progressive than expected

```{r}
all_prog_pred %>% 
  filter(party == "dem") %>% 
  arrange(.resid) %>% 
  head(5)
```
